


train_dataset:
  type: Cityscapes
  dataset_root: cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: EESPNetSeg
  backbone:
    type: EESPNet
    num_classes: 19
  s: 0.4

optimizer:
  type: sgd
  weight_decay: 0.0002

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.00000001
  power: 0.9

iters: 80000
batch_size: 8


loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.3]